import "dart:convert";
import "dart:io";

import 'package:recase/recase.dart';

void main(List<String> args) {
  File fontsConfigFile = File(args[0]);

  if (!fontsConfigFile.existsSync()) {
    print('config file not found');
    exit(0);
  }

  String content = fontsConfigFile.readAsStringSync();
  List<dynamic> icons = json.decode(content);

  List<String> generatedOutput = [
    "library awesome_icons;\n",
    "import \"package:flutter/widgets.dart\";\n",
    "import \"src/icon_data.dart\";\n\n",
    "// THIS FILE IS AUTOMATICALLY GENERATED!\n\n",
    "const Map<String, IconData> awesomeIconsMap = {\n"
  ];

  for (Map<String, dynamic> icon in icons) {
    icon.forEach((String iconName, dynamic iconUnicode) =>
        generatedOutput.add("'$iconName' : AwesomeIconData(0x$iconUnicode),\n"));
  }

  generatedOutput.add("};\n");

  generatedOutput.add("class AwesomeIcons {\n");

  for (Map<String, dynamic> icon in icons) {
    icon.forEach((String iconName, dynamic iconUnicode) =>
        generatedOutput.add("static const IconData ${iconName.camelCase} = AwesomeIconData(0x$iconUnicode);\n"));
  }

  generatedOutput.add("}\n");

  generatedOutput.add("class AwesomeIconsSnakeCase {\n");

  for (Map<String, dynamic> icon in icons) {
    icon.forEach((String iconName, dynamic iconUnicode) =>
        generatedOutput.add("static const IconData ${iconName.snakeCase} = AwesomeIconData(0x$iconUnicode);\n"));
  }

  generatedOutput.add("}\n");

  File output = File('./lib/awesome_icons.dart');
  output.writeAsStringSync(generatedOutput.join());
}
